# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://matienzo.org
title: Mark A. Matienzo
subtitle:
author:
  name: Mark A. Matienzo
  twitter: anarchivist
  picture: /images/matienzo.jpg
  url: https://matienzo.org
lang: en-US
#description: Thoughts on recordkeeping, technology, and politics

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

feed:
  path: atom.xml
email: mark@matienzo.org

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
#root: /
permalink: /:year/:title/
timezone: America/Los_Angeles # permalinks might break if this changes
#source: source
destination: _site
category_dir:
markdown: kramdown
highlighter: rouge

include:
  - _headers
  - _redirects

exclude:
  - bin/deploy
  - Gemfile
  - Gemfile.lock
  - rsync-exclude
  - config.rb
  - functions
  - node_modules
  - package.json
  - package

excerpt_separator: <!--more-->

titlecase: false       # Converts page and post titles to titlecase

theme: jekyll-theme-basically-basic

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap

collections:
  posts:
    output: true
    permalink: /:year/:title/
  notes:
    output: true
    permalink: /:year/:y_day/:title/

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      category: article
      layout: post

  -
    scope:
      path: ""
      type: notes
    values:
      category: note
      layout: note

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Begin config for Basically Basic
twitter_username: anarchivist
github_username: anarchivist
google_analytics: UA-6399155-1
disqus:
  shortname: matienzo
# End config for Basically Basically

# Begin config for Jekyll SEO Tag
twitter:
  username: anarchivist
social:
  name: Mark A. Matienzo
  links:
    - https://twitter.com/anarchivist
    - https://github.com/anarchivist
    - https://keybase.io/anarchivist
    - https://linkedin.com/in/markmatienzo
    - https://orcid.org/0000-0003-3270-1306
    - https://www.wikidata.org/wiki/Q57491060
webmaster_verifications:
  google: Cj3zranByErq0NTRdlM3c2RAkZoa3B46bcsyRVlbBBg
# End config for Jekyll SEO Tag

# Begin config for jekyll-paginate-v2
pagination:
  enabled: true
  collection: 'all'
  per_page: 10
  sort_field: date
  sort_reverse: true
  title: ':title - page :num of :max'
  trail:
    before: 0
    after: 0
  permalink: /page/:num/
autopages:
  enabled: true
  collections:
    layouts:
      - home.html
    title: :coll
    permalink: /:coll/
  tags:
    enabled: false
  categories:
    enabled: false
# End config for jekyll-paginate-v2
